### ISSUE TITLE
Will prereleases automatically be released on GitHub as such?

### ISSUE THREAD

**Issue by MicaelJarniac** [python-semantic-release/upload-to-gh-release#1]
If a release is generated by Python Semantic Release with the `tool.semantic_release.branches.*.prerelease = true` option, will this action upload it to GitHub as a prerelease?

**Comment by MicaelJarniac** [comment]
From reading the docs here, it seems I need to specify the tag manually, from the output of the Python Semantic Release action. Is that the case? I'm slightly confused.

**Comment by codejedi365** [comment]
@MicaelJarniac, first I would like to apologize that your issue never got a response when requested, I was not one of the maintainers at that time but I will do my best to answer your question even if you have understandably moved on or figured it out already.

> If a release is generated by Python Semantic Release with the `tool.semantic_release.branches.*.prerelease = true` option, will this action upload it to GitHub as a prerelease?

Yes, this action uploads artifacts to an existing release if found. If a release is not found, it will log a warning and end. The prerelease setting itself does not affect the `publish` command as `publish` expects the release to already exist. The prerelease value of the release is set upon creation of the release. Our example in the README expects the regular Python Semantic Release action to have created the VCS release prior to this action.

> From reading the docs here, it seems I need to specify the tag manually, from the output of the Python Semantic Release action. Is that the case? I'm slightly confused.

It is an optional parameter. Our example passes it specifically from the actual PSR action. If you don't provide the tag then it will default to `latest` which means this action will look to git for the latest tag and upload the distribution artifacts to that release.
