### ISSUE TITLE
Publish tags/releases for this action

### ISSUE THREAD

**Issue by nejch** [python-semantic-release/upload-to-gh-release#2]
People who use semver might be a little wary of tracking `main` for publishing their own releases so it might be useful having this tagged here as well if it's recommended for use in release workflows ;)

**Comment by afuetterer** [comment]
Yes, that would be nice. Can you just copy the version of python-semantic-release to this action, e.g. 8.3.0?

**Comment by codejedi365** [comment]
@nejch, @afuetterer, well said! Currently working on replicating the version used in the action to align to the PSR version as suggested.

**Comment by codejedi365** [comment]
Completed the releasing of all versions from `v8.7.0` (original main) to `v9.7.3`.

**Comment by afuetterer** [comment]
Awesome, thank you.
