### ISSUE TITLE
Use a lockfile for dependencies or pin all transitive dependencies

### ISSUE THREAD

**Issue by nejch** [python-semantic-release/upload-to-gh-release#25]
We just had to yank a python-gitlab release due to a regression and had to do another release (https://github.com/python-gitlab/python-gitlab/issues/2981). Obviously, we need to find a way to test this on our end and :sweat_smile: 

But since this action installs the package without a lockfile, it also installed the latest python-gitlab dependency and failed immediately. I'd suggest using something like poetry or uv (or even a generated requirements.txt with all the deps) to explicitly manage transitive dependencies as well to avoid more issues for users.

For us this caused a little bootstrapping issue (we couldn't release a new python-gitlab version to fix the original issue) which is an edge case, but for other users it would still be better IMO to have reproducible builds and more safety :+1:

**Comment by codejedi365** [comment]
I appreciate the recommendation, however, this action is only a wrapper around the python-semantic-release wheel package.  Given that it is pulling the wheel from pypi, It is not plausible to utilize a lockfile for the action.  

I am a huge advocate for better dependency management but unfortunately python has not solved the primary virtual environment issue which undermines the ability and effectiveness of lockfiles by the consumer.  Lockfiles are only valuable currently for the CI environment of the project that includes it and if they are using a lockfile compatible installer backend. Consumers of the package do not gain any value from lockfiles at this time.

This is not something I can or will prevent. It is most important that the library developer tests before release to prevent dependent projects from breaking upon imports. Thankfully you have already accomplished in a timely manner with the package yank.
