### ISSUE TITLE
Missing Maintainer Permissions for project

### ISSUE THREAD

**Issue by codejedi365** [python-semantic-release/upload-to-gh-release#3]
@bernardcooke53, @python-semantic-release/team, I have some updates to make to this gh-action now that we are over `v9` on PSR.  Can one of you add me as a maintainer for this repository? Thanks!

**Comment by codejedi365** [comment]
@relekang

**Comment by bernardcooke53** [comment]
Hey @codejedi365, I just added the whole team - hopefully you should be able to admin!

**Comment by codejedi365** [comment]
Excellent! Thank you @bernardcooke53, I will try it out later today
